import mongoose from 'mongoose';
import crypto from 'crypto';

const taskSchema = new mongoose.Schema({
  uuid: { type: String, unique: true, required: true, default: () => crypto.randomUUID() },
  title: { type: String, required: true, trim: true },
  description: { type: String, trim: true },
  dueDate: { type: Date },
  recurrence: { type: String, enum: ['none', 'daily', 'weekly', 'monthly'], default: 'none' },
  priority: { type: String, enum: ['low', 'normal', 'high'], default: 'normal' },
  // How the task came to exist: 'manual' (someone created it) or 'system'
  // (auto-generated by a service, e.g. HR/vehicle compliance). Drives UI badges
  // and lets people tell a reminder apart from a hand-assigned task.
  source: { type: String, enum: ['manual', 'system'], default: 'manual', index: true },
  userId: { type: mongoose.Schema.Types.ObjectId, ref: 'user', required: true, index: true },
  contractId: { type: mongoose.Schema.Types.ObjectId, ref: 'contract', default: null },
  completed: { type: Boolean, default: false, index: true },
  completedAt: { type: Date, default: null },
  // Who ticked it off. null with autoResolved=true means the system closed it
  // (e.g. a compliance date was renewed, so the reminder no longer applies).
  completedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'user', default: null },
  autoResolved: { type: Boolean, default: false },
  // Recurring tasks: set once the next occurrence has been created, so the
  // completion handler and the recurring-tasks job never both spawn one.
  nextSpawnedAt: { type: Date, default: null },
  // System tasks: stable identity of the thing being reminded about, e.g.
  // 'vehicle:<id>:motExpiryDate:2026-11-01'. Shared by every admin's copy, so
  // completing one completes them all and a completed reminder isn't re-created.
  systemKey: { type: String, default: null, index: true }
}, {
  timestamps: true
});

// Validation: if recurrence is not 'none', a dueDate must exist.
taskSchema.pre('validate', function(next) {
  if (this.recurrence && this.recurrence !== 'none' && !this.dueDate) {
    return next(new Error('Recurring tasks must have a dueDate.'));
  }
  next();
});

// Helpful compound index to accelerate dashboard categorisation queries.
// Not unique to avoid migration issues with legacy duplicates.
taskSchema.index({ userId: 1, completed: 1, dueDate: 1 });


export default {
  modelName: 'task',
  schema: taskSchema
};
