module.exports = {
  assignment: {
    title: 'Assignments',
    linkField: 'title',
    hideFields: ['__v', '_id','createdAt', 'updatedAt','uuid'],
    sortField: 'createdAt',
    sortOrder: -1,
    department: ['management'],
  },
  attendance: {
    title: 'Attendances',
    linkField: 'date',
    hideFields: ['__v', '_id','createdAt', 'updatedAt','uuid'],
    fieldOrder: ['date', 'type', 'employeeId', 'subcontractorId', 'hoursWorked', 'payRate', 'dayRate', 'locationId', 'projectId'],
    sortField: 'date',
    sortOrder: 1,
    department: ['management'],
  },
  contract: {
    title: 'Contracts',
    linkField: 'title',
    labelOverrides: {
      uuid: 'Contract ID',
      title: 'Title',
      location: 'Site Location',
      status: 'Current Status',
      startDate: 'Start Date',
      endDate: 'End Date',
    },
    hideFields: ['__v', '_id','createdAt', 'updatedAt','uuid'],
    sortField: 'createdAt',
    sortOrder: -1,
    department: ['management'],
  },
  customer: {
    title: 'Customers',
    linkField: 'Name',
    hideFields: ['__v', '_id','createdAt', 'updatedAt','uuid','Discount','CountryName','Created', 'Updated','Website','Notes','CustomerID','Code'],
    fieldOrder: ['Name'],
    sortField: 'Name',
    sortOrder: 1,
    department: ['kashflow'],
    deny: ['c','d'],
  },
  employee: {
    title: 'Employees',
    linkField: 'name',
    hideFields: ['__v', '_id','createdAt', 'updatedAt','uuid'],
    fieldOrder: ['name', 'email', 'phoneNumber', 'position', 'status', 'type','dailyRate', 'hourlyRate', 'hireDate', 'managerId'],
    sortField: 'name',
    sortOrder: 1,
    department: ['payroll','human-resources'],
  },
  holiday: {
    title: 'Holidays',
    linkField: 'title',
    sortField: 'title',
    sortOrder: 1,
    department: ['human-resources'],
    deny: ['c','r','u','d'],
  },
  invoice: {
    title: 'Invoices',
    linkField: 'InvoiceNumber',
    hideFields: ['__v','_id','createdAt','updatedAt','uuid','InvoiceDBID','DeliveryAddress','CurrencyCode','ExchangeRate','PermaLink','UseCustomDeliveryAddress','ReadableString','EstimateCategory','CustomerID','Paid','CISRCNetAmount','CISRCVatAmount','IsCISReverseCharge','Customer','SuppressTotal'],
    sortField: 'InvoiceNumber',
    sortOrder: 1,
    department: ['kashflow'],
    deny: ['c','d'],
  },
  job: {
    title: 'Jobs',
    linkField: 'JobRef',
    hideFields: ['__v', '_id','createdAt', 'updatedAt','uuid'],
    sortField: 'JobRef',
    sortOrder: 1,
    department: ['management'],
  },
  location: {
    title: 'Locations',
    linkField: 'name',
    hideFields: ['__v', '_id','createdAt', 'updatedAt','uuid'],
    sortField: 'name',
    sortOrder: 1,
    department: ['management'],
  },
  meta: {
    deny: ['c','r','u','d','l'],
  },
  project: {
    title: 'Projects',
    linkField: 'Number',
    sortField: 'Number',
    sortOrder: 1,
    hideFields: ['__v','_id','createdAt','updatedAt','uuid','ID','Date1','Date2'],
    department: ['kashflow'],
    deny: ['c','d'],
    handlesDocuments: true,
  },
  quote: {
    title: 'Quotes',
    linkField: 'InvoiceNumber',
    hideFields: ['__v','_id','createdAt','updatedAt','uuid','InvoiceDBID','SuppressTotal','DueDate','DeliveryAddress','CurrencyCode','ExchangeRate','PermaLink','UseCustomDeliveryAddress','ReadableString','EstimateCategory','CustomerID','Paid','CISRCNetAmount','CISRCVatAmount','IsCISReverseCharge','Customer'],
    fieldOrder: ['InvoiceNumber', 'InvoiceDate', 'CustomerName', 'NetAmount', 'VATAmount', 'AmountPaid'],
    sortField: 'InvoiceNumber',
    sortOrder: 1,
    department: ['kashflow'],
    deny: ['c','d'],
  },
  receipt: {
    title: 'Receipts',
    linkField: 'InvoiceNumber',
    hideFields: ['__v','_id','createdAt','updatedAt','uuid','InvoiceDBID','DeliveryAddress','CurrencyCode','ExchangeRate','PermaLink','UseCustomDeliveryAddress','ReadableString','EstimateCategory','CustomerID','Paid','CISRCNetAmount','CISRCVatAmount','IsCISReverseCharge','Customer'],
    fieldOrder: ['InvoiceNumber', 'InvoiceDate', 'CustomerName', 'NetAmount', 'VATAmount', 'AmountPaid'],
    sortField: 'InvoiceNumber',
    sortOrder: 1,
    department: ['kashflow'],
    deny: ['c','d'],
  },
  session: {
    deny: ['c','r','u','d','l'],
  },
  supplier: {
    title: 'Suppliers',
    linkField: 'Name',
    hideFields: ['__v','_id','createdAt','updatedAt','uuid','Created','Updated','SupplierID','EC','TradeBorderType','Contact','ContactTitle','ContactFirstName','ContactLastName','Telephone','Fax','Mobile','Website','CurrencyID','PaymentTerms'],
    fieldOrder: ['Name', 'Subcontractor', 'CISRate', 'CISNumber'],
    sortField: 'Name',
    sortOrder: 1,
    department: ['kashflow','construction-industry-scheme'],
    deny: ['c','d'],
    actions: [{
      label: 'Change',
      class: 'warning',
      href: row => `/supplier/change/${row.uuid}`
    }],
    description: {
      manage: 'Manage suppliers and subcontractors.',
    },
  },
  task: {
    title: 'Tasks',
    linkField: 'title',
    hideFields: ['__v','_id','createdAt','updatedAt','uuid','password'],
    sortField: 'title',
    sortOrder: 1,
    department: ['human-resources'],
  },
  user: {
    title: 'Users',
    linkField: 'username',
    hideFields: ['__v', '_id','createdAt', 'updatedAt','uuid', 'password', 'totpSecret', 'totpEnabled'],
    fieldOrder: ['username', 'email', 'role', 'status', 'lastLogin'],
    sortField: 'username',
    sortOrder: 1,
    department: ['human-resources'],
  },
  vehicle: {
    title: 'Vehicles',
    linkField: 'registrationNumber',
    hideFields: ['__v', '_id','createdAt', 'updatedAt','uuid'],
    sortField: 'registrationNumber',
    sortOrder: 1,
    department: ['management'],
  },
  holidayDismissal: {
    title: 'Dismissed Holidays',
    description: {
      manage: 'Manage company holidays'
    },
    linkField: 'uuid',
    sortField: 'dismissedAt',
    sortOrder: 1,
    department: ['human-resources'],
    deny: ['c','u'],
  },
  holidayCustom: {
    title: 'Company Holidays',
    description: {
      create: 'Create a company holiday',
      manage: 'Manage company holidays'
    },
    linkField: 'title',
    sortField: 'title',
    sortOrder: 1,
    department: ['human-resources'],
  }
};