import mongoose from 'mongoose';
const p = __hcs_schemas.purchase;
import __purchase from './mongoose/models/mongoose/REST/purchase.js';
import __hcs_schemas from '@cappytech/hcs-schemas';
const { schema } = __purchase;
console.log('fields:', JSON.stringify(Object.keys(p.fields)));
console.log('indexes:', JSON.stringify(p.indexes));
console.log('Schema paths:', Object.keys(schema.paths));
console.log('Number path instance:', schema.path('Number')?.instance);
console.log('number path instance:', schema.path('number')?.instance);
console.log('data path instance:', schema.path('data')?.instance);
console.log('data.Number path instance:', schema.path('data.Number')?.instance);
console.log('schema options:', JSON.stringify(schema.options));
