// Generated by scripts/generate-tailwind-safelist.js; tracked in git and
// copied into the Docker builder stage, so a static import is safe.
import __tailwind_safelist from './tailwind.safelist.js';
import __forms from '@tailwindcss/forms';
import __typography from '@tailwindcss/typography';

/**** Tailwind config ****/
/** @type {import('tailwindcss').Config} */
// Auto-merge generated safelist with static entries.
const generatedSafelist = Array.isArray(__tailwind_safelist) ? __tailwind_safelist : [];

const staticSafelist = [
  // Dashboard tile dynamic button classes (not directly in templates)
  'bg-blue-700', 'hover:bg-blue-800',
  'bg-green-700', 'hover:bg-green-800',
  'bg-blue-800', 'bg-green-800',
  // Common text colors potentially applied via config
  'text-green-600', 'text-green-700', 'text-blue-700'
];

export default {
  darkMode: 'class',
  content: [
    './mongoose/views/**/*.ejs',
    './public/js/**/*.js',
    './mongoose/config/**/*.js'
  ],
  safelist: Array.from(new Set([...staticSafelist, ...generatedSafelist])),
  theme: {
    extend: {
      colors: {
        brand: {
          DEFAULT: '#047857',
          light: '#10b981',
          dark: '#065f46'
        }
      }
    }
  },
  plugins: [
    __forms,
    __typography
  ]
};
