import logger from '../../services/loggerService.js';
import emailService from '../../services/emailService.js';
import emailLayout from '../../services/emailLayout.js';
import kfSession from '../../services/kashflowSessionService.js';
const axios = kfSession.kfAxios;
import mdb from './mongooseDatabaseService.js';
import hcsSyncService from './hcsSyncService.js';

const KF_BASE = (
  process.env.KASHFLOW_API_BASE_URL || 'https://api.kashflow.com/v2'
).replace(/\/+$/, '');

// ── Financial helpers ────────────────────────────────────────────────────────

/**
 * Computes income/expenditure financials for a REST project document.
 * Returns { incomeTarget, incomeActual, incomeDiff, expTarget, expActual, expDiff, atRisk }
 */
function computeFinancials(project) {
  const incomeTarget = project.TargetSalesAmount ?? 0;
  const incomeActual = project.ActualSalesAmount ?? 0;
  const incomeDiff   = incomeActual - incomeTarget;

  const expTarget = project.TargetPurchasesAmount ?? 0;
  const expActual = project.ActualPurchasesAmount ?? 0;
  const expDiff   = expActual - expTarget;

  return {
    incomeTarget,
    incomeActual,
    incomeDiff,
    expTarget,
    expActual,
    expDiff,
    atRisk: incomeActual > 0 && incomeDiff < 0,
  };
}

// ── Financial check (email alerts) ──────────────────────────────────────────

/**
 * Reads all active KashFlow projects from the REST namespace, computes
 * financial health, and sends an alert email for any project where the income
 * difference is negative (actual < target).
 *
 * @param {object} [opts]
 * @param {string} [opts.notifyEmail] - Address to send alert to (required to send email)
 * Returns { checked, atRisk, emailSent }
 */
async function checkProjectFinancials({ notifyEmail } = {}) {
  const RestProject = mdb.REST?.project;
  if (!RestProject) throw new Error('REST project model not available');

  const projects = await RestProject.find({
    Status: { $in: ['Active', 'active', 1, '1'] },
  }).lean();

  // KashFlow stores Status as a string (e.g. 'Active') or numeric 1
  // Broaden: exclude only Completed/Archived
  const activeProjects = projects.length
    ? projects
    : await RestProject.find({
        $nor: [
          { Status: 'Completed' },
          { Status: 'Archived' },
          { StatusName: 'Completed' },
        ],
      }).lean();

  const withFinancials = activeProjects.map(p => ({
    ...p,
    _financials: computeFinancials(p),
  }));

  const atRisk = withFinancials.filter(p => p._financials.atRisk);

  let emailSent = false;
  let emailError = null;
  if (atRisk.length > 0) {
    const to = notifyEmail ||
      process.env.NOTIFY_EMAIL ||
      process.env.SMTP_FROM ||
      process.env.SMTP_USER;

    if (to) {
      const fmt = n => `£${Number(n).toFixed(2)}`;
      const baseUrl = process.env.BASE_URL || '';
      const kfBase = 'https://app.kashflow.com/editProject.asp';

      const { escapeHtml, dataTable, link, note, BRAND } = emailLayout;

      // Five columns of currency is the worst case for a phone, so this goes
      // through emailLayout.dataTable — a normal table on desktop, one labelled
      // card per project below 600px.
      const rows = atRisk.map(p => [
        {
          html: p.Id
            ? link(`${p.Number} — ${p.Name || '—'}`, `${kfBase}?id=${p.Id}`)
            : escapeHtml(`${p.Number} — ${p.Name || '—'}`),
        },
        { text: p.CustomerName || '—' },
        { text: fmt(p._financials.incomeTarget), align: 'right' },
        { text: fmt(p._financials.incomeActual), align: 'right' },
        {
          text: fmt(p._financials.incomeDiff),
          align: 'right',
          style: 'color:#dc2626;font-weight:600;',
        },
      ]);

      const html = emailLayout.renderDocument({
        title: 'KashFlow projects below income target',
        preheader: `${atRisk.length} project${atRisk.length !== 1 ? 's are' : ' is'} below income target.`,
        contentHtml: `
            <h1 class="email-heading" style="margin:0 0 16px;font-size:22px;line-height:29px;font-weight:700;color:${BRAND};">Projects below income target</h1>
            <p style="margin:0 0 4px;"><strong>${atRisk.length} KashFlow project${atRisk.length !== 1 ? 's are' : ' is'} below income target.</strong></p>
            ${dataTable(['Project', 'Customer', 'Target', 'Actual', 'Shortfall'], rows)}
            <p style="margin:16px 0 0;font-size:13px;">${link('View overview →', `${baseUrl}/overview/projects`)}</p>`,
        afterHtml: note(`
            <p style="margin:0 0 8px;">
              This is an automated financial alert generated by the Heron Constructive Solutions
              internal business system. It compares each active KashFlow project's income against
              its target and flags any project that is falling short, so the team can review it.
              No action is required unless you are responsible for the projects listed above.
            </p>
            <p style="margin:0 0 8px;">
              <strong>Confidential:</strong> This email and any attachments contain confidential
              and commercially sensitive information intended solely for the named recipient(s).
              If you are not the intended recipient, you must not read, copy, distribute or rely
              on any part of it.
            </p>
            <p style="margin:0;">
              If you have received this email in error, please notify us immediately at
              <a class="email-link" href="mailto:admin@heroncs.co.uk" style="color:inherit;">admin@heroncs.co.uk</a>
              and permanently delete it from your system.
              Heron Constructive Solutions LTD, 103 Herondale Road, Mossley Hill, Liverpool, L18 1JZ.
            </p>`),
      });

      const text = atRisk
        .map(
          p =>
            `${p.Number} — ${p.Name || '—'} (${p.CustomerName || '—'}): target ${fmt(p._financials.incomeTarget)}, actual ${fmt(p._financials.incomeActual)}, shortfall ${fmt(p._financials.incomeDiff)}`,
        )
        .join('\n')
        .concat(
          '\n\n' +
            '----------------------------------------------------------------------\n' +
            'This is an automated financial alert from the Heron Constructive Solutions\n' +
            'internal business system. It flags active KashFlow projects whose income is\n' +
            'below target. No action is required unless you are responsible for the\n' +
            'projects listed above.\n\n' +
            'CONFIDENTIAL: This email contains confidential and commercially sensitive\n' +
            'information intended solely for the named recipient(s). If you are not the\n' +
            'intended recipient, you must not read, copy, distribute or rely on any part\n' +
            'of it.\n\n' +
            'If you have received this email in error, please notify us immediately at\n' +
            'admin@heroncs.co.uk and permanently delete it from your system.\n' +
            'Heron Constructive Solutions LTD, 103 Herondale Road, Mossley Hill,\n' +
            'Liverpool, L18 1JZ.',
        );

      // The check itself has already succeeded by this point. A delivery
      // failure (SMTP down, wrong port, etc.) must not discard the results —
      // capture it and report it as a partial success to the caller.
      try {
        await emailService.sendMail({
          to,
          subject: `⚠ ${atRisk.length} KashFlow project(s) below income target`,
          html,
          text,
        });
        emailSent = true;
      } catch (mailErr) {
        emailError = mailErr.message;
        logger.error(
          `[kashflowProjectService] Financial check ran but the alert email could not be sent: ${mailErr.message}`,
        );
      }
    } else {
      logger.warn('[kashflowProjectService] No notify email set — skipping alert email');
    }
  }

  logger.info(
    `[kashflowProjectService] Financial check complete: ${activeProjects.length} checked, ${atRisk.length} at risk, email sent: ${emailSent}`,
  );

  return { checked: activeProjects.length, atRisk: atRisk.length, emailSent, emailError, projects: withFinancials };
}

// ── Mark project complete via KashFlow API ───────────────────────────────────

/**
 * Sends PUT /projects/{number} to KashFlow with Status = "Completed".
 * Fetches the existing project first so the PUT body contains all required fields.
 */
async function markProjectComplete(projectNumber) {
  if (!projectNumber) throw new Error('projectNumber is required');

  await kfSession.withKfAuth(async (token) => {
    const headers = { Authorization: `KfToken ${token}` };

    // Fetch the current project so we can send a complete PUT body
    const { data: existing } = await axios.get(
      `${KF_BASE}/projects/${projectNumber}`,
      { headers },
    );

    // Only send the fields the PUT endpoint accepts
    const body = {
      Number:                existing.Number,
      Name:                  existing.Name,
      Reference:             existing.Reference,
      Description:           existing.Description,
      Note:                  existing.Note,
      Status:                'Completed',
      StartDate:             existing.StartDate,
      EndDate:               existing.EndDate,
      CustomerCode:          existing.CustomerCode,
      TargetSalesAmount:     existing.TargetSalesAmount,
      TargetPurchasesAmount: existing.TargetPurchasesAmount,
      ExcludeVAT:            existing.ExcludeVAT,
    };

    await axios.put(
      `${KF_BASE}/projects/${projectNumber}`,
      body,
      { headers },
    );
  });

  logger.info(`[kashflowProjectService] Marked project ${projectNumber} as Completed in KashFlow`);

  // The KashFlow write succeeded, but the local REST-namespace copy (maintained
  // by hcs-sync) is now stale — it still shows the project as active. Re-pull it
  // from KashFlow via hcs-sync so the projects overview reflects the change.
  await refreshLocalProject(projectNumber);
}

/**
 * Refresh a single project's local REST-namespace copy after a write to
 * KashFlow. Primary path: ask hcs-sync to re-pull it (authoritative, full
 * document). Fallback: if hcs-sync is unreachable, patch the local Status
 * directly so the overview stays consistent.
 */
async function refreshLocalProject(projectNumber) {
  try {
    await hcsSyncService.pullEntity('project', projectNumber);
    logger.info(`[kashflowProjectService] Re-synced project ${projectNumber} via hcs-sync`);
    return;
  } catch (err) {
    logger.warn(
      `[kashflowProjectService] hcs-sync re-pull failed for project ${projectNumber}: ${err.message} — falling back to local Status patch`,
    );
  }

  // Fallback: keep the local copy consistent even if hcs-sync is down.
  try {
    const RestProject = mdb.REST?.project;
    if (RestProject) {
      await RestProject.updateOne(
        { Number: projectNumber },
        { $set: { Status: 'Completed' } },
      );
      logger.info(`[kashflowProjectService] Patched local project ${projectNumber} Status=Completed (fallback)`);
    }
  } catch (patchErr) {
    logger.error(
      `[kashflowProjectService] Fallback local patch failed for project ${projectNumber}: ${patchErr.message}`,
    );
  }
}

export default { checkProjectFinancials, markProjectComplete, computeFinancials };
