import { describe, it } from 'node:test';
import assert from 'node:assert/strict';

import apiDocs, { handWrittenApiDocs } from '../mongoose/config/apiDocsConfig.js';
import apiDocsGenerated from '../mongoose/config/apiDocsGenerated.js';

/**
 * /help/api renders these two files: prose written by hand, plus the rest of
 * KashFlow's published Swagger surface generated by scripts/generate-api-docs.mjs.
 * The merge between them has sharp edges, and each of these pins one.
 */

const allOps = (groups) => groups.flatMap((g) => g.operations);
const METHODS = new Set(['GET', 'POST', 'PUT', 'PATCH', 'DELETE']);

describe('apiDocsConfig', () => {
  it('gives every operation a unique id', () => {
    // op.id is the anchor the sidebar links to; a duplicate silently sends two
    // entries to the same place.
    const seen = new Map();
    for (const op of allOps(apiDocs)) {
      assert.equal(seen.has(op.id), false, `duplicate operation id: ${op.id} (${op.method} ${op.path})`);
      seen.set(op.id, op);
    }
  });

  it('gives every group the fields the view reads', () => {
    for (const group of apiDocs) {
      for (const key of ['tag', 'icon', 'colorClass', 'bgClass', 'borderClass']) {
        assert.ok(group[key], `group ${group.tag} is missing ${key}`);
      }
      assert.ok(Array.isArray(group.operations) && group.operations.length, `group ${group.tag} has no operations`);
    }
  });

  it('lists each group tag once, so merged groups do not render twice', () => {
    const tags = apiDocs.map((g) => g.tag);
    assert.deepEqual(tags.length, new Set(tags).size, `repeated tags: ${tags.filter((t, i) => tags.indexOf(t) !== i)}`);
  });

  it('gives every operation the fields the view reads', () => {
    for (const op of allOps(apiDocs)) {
      assert.ok(op.id, `operation on ${op.path} has no id`);
      assert.ok(METHODS.has(op.method), `${op.id} has method ${op.method}`);
      assert.ok(op.path && op.path.startsWith('/'), `${op.id} has path ${op.path}`);
      assert.ok(op.summary, `${op.id} has no summary`);
      if (op.request) assert.ok(Array.isArray(op.request.fields), `${op.id} request.fields is not an array`);
      if (op.response) assert.ok(Array.isArray(op.response.fields), `${op.id} response.fields is not an array`);
      if (op.notes) assert.ok(Array.isArray(op.notes), `${op.id} notes is not an array`);
    }
  });

  it('leaves handWrittenApiDocs unmerged', () => {
    // The generator reads this export to decide what still needs generating.
    // mergeGenerated() used to mutate it in place, which made every generated
    // operation look hand-written — the next run emitted an empty file.
    const generatedCount = allOps(apiDocsGenerated).length;
    assert.equal(
      allOps(handWrittenApiDocs).length + generatedCount,
      allOps(apiDocs).length,
      'the merged docs should be exactly hand-written + generated',
    );
    assert.ok(generatedCount > 0, 'apiDocsGenerated is empty — regenerate it from the spec');
    assert.equal(
      allOps(handWrittenApiDocs).some((op) => op.generated),
      false,
      'a generated operation leaked into handWrittenApiDocs',
    );
  });

  it('marks generated operations and leaves hand-written prose unmarked', () => {
    // How the page tells curated wording from spec-derived wording.
    for (const op of allOps(apiDocsGenerated)) {
      assert.equal(op.generated, true, `${op.id} is in the generated file but not marked generated`);
    }
  });

  it('documents no operation twice across the two files', () => {
    const key = (op) => `${op.method} ${op.path.toLowerCase().replace(/\{[^}]*\}/g, '{}')}`;
    const hand = new Set(allOps(handWrittenApiDocs).map(key));
    for (const op of allOps(apiDocsGenerated)) {
      assert.equal(hand.has(key(op)), false, `${key(op)} is documented by hand and generated again`);
    }
  });
});
