'use strict';

const apiDocs = require('../config/apiDocsConfig');

const helpContent = [
  // ─────────────────────────────────────────────────────────────────────────
  //  ROLE GUIDE  — first thing every user sees
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'your-role',
    title: 'Your Role & Access',
    icon: 'bi-person-badge',
    colorClass: 'text-violet-600 dark:text-violet-400',
    bgClass: 'bg-violet-500',
    borderClass: 'border-violet-500',
    articles: [
      {
        id: 'role-overview',
        title: 'What Your Role Controls',
        badge: 'All roles',
        description: 'Your role determines every page, list, and action available to you. Menu items, buttons, and data are all filtered to your role — you will never see an area you do not have access to.',
        fields: [
          { name: 'Admin', required: '', description: 'Full access to every module: employees, fleet, attendance, holidays, tasks, CIS, finance, documents, and system settings.' },
          { name: 'Accountant', required: '', description: 'Read-only access to all financial data: invoices, purchases, suppliers, customers, projects, quotes, nominals. Also sees the CIS dashboard and payroll summaries.' },
          { name: 'Employee', required: '', description: 'Submit and view your own attendance records. See your own employee profile, holiday balance, and any vehicles assigned to you.' },
          { name: 'Subcontractor', required: '', description: 'Submit and view your own attendance records. View your own supplier record, your purchase invoices, your CIS return, and any vehicles assigned to you.' },
          { name: 'Client', required: '', description: 'View your own customer record, invoices raised against you, quotes, and projects.' },
          { name: 'HMRC', required: '', description: 'Read-only view of all supplier (subcontractor) records and the CIS dashboard for verification purposes.' },
          { name: 'None', required: '', description: 'Account created but no role assigned yet. Contact your administrator to have your role set before you can access any data.' },
        ],
        notes: [
          'If you believe your role is incorrect or you need access to an additional area, contact your system administrator.',
          'Your current role is always shown on your profile page (/user/profile).',
        ],
      },
      {
        id: 'your-profile',
        title: 'Your Profile & Account Settings',
        badge: 'All roles',
        description: 'Manage your login details, display name, and security settings from your account page.',
        steps: [
          'Navigate to your profile by clicking the user icon in the top navigation bar, or go to /user/profile.',
          'Your profile displays your role, linked entity (employee, supplier, or customer), and account status.',
          'To change your password: go to Account Settings and enter your current password, then your new one.',
          'To update your display name or email address, edit the relevant fields and save.',
          'If your email address is unverified a banner will appear — use the link in the verification email sent to you at registration.',
        ],
        notes: [
          'Changing your email address will require re-verification.',
        ],
      },
      {
        id: 'two-factor-auth',
        title: 'Two-Factor Authentication (2FA)',
        badge: 'All roles',
        description: 'Add a second layer of login security using an authenticator app (Google Authenticator, Authy, Microsoft Authenticator, etc.).',
        steps: [
          'Go to Account Settings → Two-Factor Authentication.',
          'Scan the QR code displayed on screen with your authenticator app.',
          'Enter the 6-digit code generated by the app to verify setup.',
          'From now on, every login will ask for your password and then your 6-digit code.',
          'To disable 2FA, return to Account Settings and confirm with your current 6-digit code.',
        ],
        notes: [
          '2FA secrets are encrypted at rest — they are never stored in plain text.',
          'If you lose access to your authenticator, contact your administrator to reset 2FA on your account.',
        ],
      },
      {
        id: 'hmrc-role',
        title: 'HMRC User Access',
        badge: 'HMRC',
        description: 'The HMRC role provides read-only access to supplier (subcontractor) records and the full CIS dashboard and returns — for verification and compliance audit purposes.',
        fields: [
          { name: 'Supplier Records', required: '', description: 'Read-only access to all supplier records — verify CIS numbers (UTRs), withholding tax flags, and HMRC verification numbers.' },
          { name: 'CIS Dashboard', required: '', description: 'View monthly CIS deduction summaries for all subcontractors at /CIS/Dashboard/:year/:month.' },
          { name: 'CIS Returns', required: '', description: 'Access the returns form (/CIS/returns/form) and view all monthly and yearly CIS return reports.' },
          { name: 'Subcontractors Overview', required: '', description: 'The overview at /overview/subcontractors shows all CIS subcontractors with rates, verification numbers, and payment totals.' },
        ],
        notes: [
          'The HMRC role is read-only — no records can be created, edited, or deleted.',
          'If data appears out of date, ask your administrator to trigger a KashFlow sync from the sync dashboard.',
        ],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  //  GETTING STARTED
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'getting-started',
    title: 'Getting Started',
    icon: 'bi-rocket-takeoff',
    colorClass: 'text-green-600 dark:text-green-400',
    bgClass: 'bg-green-500',
    borderClass: 'border-green-500',
    articles: [
      {
        id: 'dashboard-overview',
        title: 'Your Dashboard',
        badge: 'All roles',
        description: 'The dashboard is your home page. What you see depends on your role — admins see tasks and overviews, employees and subcontractors see their own attendance shortcuts.',
        steps: [
          'Your role and name appear at the top right. Click the user icon to access your profile.',
          'Admins and accountants: the task summary strip shows open, overdue, due today, and due-this-week counts.',
          'Use the Quick Add Task form to create a task without leaving the dashboard (admin only).',
          'The Overviews grid at the bottom links to role-appropriate summary dashboards — Fleet, HR, Finance, Projects, Documents, Subcontractors, Admin.',
          'Employees and subcontractors: your dashboard shows a direct link to submit attendance and view your recent records.',
        ],
        notes: [
          'Vehicle compliance tasks are auto-generated — you do not need to create them manually.',
          'Overviews only appear on the dashboard if your role has access to that department.',
        ],
      },
      {
        id: 'navigation',
        title: 'Navigation',
        badge: 'All roles',
        description: 'The top navigation bar links to every section your role can access. Items are shown or hidden based on your role and department permissions — you will never see a link to an area you cannot use.',
        steps: [
          'Click the Home icon to return to the dashboard at any time.',
          'Each icon in the nav bar represents a department (e.g. Attendance, Finance, Fleet).',
          'The Theme toggle (sun / moon icon) switches between light and dark mode — saved in your browser.',
          'On small screens, icon labels hide but icons remain clickable.',
          'If an expected section is missing from the nav, your role may not include that department — contact your administrator.',
        ],
        notes: [],
      },
      {
        id: 'first-login',
        title: 'First Login & Setup',
        badge: 'All roles',
        description: 'Steps to take after your account is first created.',
        steps: [
          'Log in with the email and password provided by your administrator.',
          'Verify your email address by clicking the link in the verification email sent to you.',
          'Set up Two-Factor Authentication (2FA) for added security — see the 2FA article in the Your Role & Access section.',
          'Review your profile (/user/profile) to confirm your name, role, and linked record are correct.',
          'If your role shows as "None", contact your administrator — you will not be able to access any data until a role is assigned.',
        ],
        notes: [
          'Your administrator may have pre-linked your account to an employee, supplier, or customer record. If this link is missing, some features may not work correctly.',
        ],
      },
      {
        id: 'list-views',
        title: 'List Views, Search & Filters',
        badge: 'All roles',
        description: 'Every entity in the system — employees, invoices, suppliers, vehicles, and more — has a paginated list view with built-in search, filters, and tabs.',
        steps: [
          'Navigate to any list page (e.g. /invoices, /suppliers, /employees).',
          'Use the search box at the top to filter records by keyword — searches key fields such as name, number, or reference.',
          'Apply column filters to narrow results by status, date range, or other criteria specific to that entity.',
          'Switch between tabs (e.g. All, Pending, Approved, Overdue) to see predefined subsets of the data.',
          'Results are paginated — use the Previous / Next buttons or page number links at the bottom to navigate.',
          'Click any row to open the full detail view for that record.',
        ],
        notes: [
          'Non-admin users only see records scoped to their own account — the same list view is reused for all roles.',
          'Search and filter state is not saved between page loads — re-enter criteria if you navigate away.',
        ],
      },
    ],
  },
  // ─────────────────────────────────────────────────────────────────────────
  //  ATTENDANCE
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'attendance',
    title: 'Attendance',
    icon: 'bi-calendar-check',
    colorClass: 'text-blue-600 dark:text-blue-400',
    bgClass: 'bg-blue-500',
    borderClass: 'border-blue-500',
    articles: [
      {
        id: 'submitting-attendance',
        title: 'Submitting Your Attendance',
        badge: 'Employee / Subcontractor',
        description: 'As an employee or subcontractor, you submit your own attendance record each working day. Records start as Pending and must be approved by an administrator before they count toward payroll or holiday balances.',
        steps: [
          'Go to Attendance → Submit (/attendance/submit).',
          'Select the date the record is for.',
          'Choose an attendance type: Work, Training, Sick, Holiday, Leave, or Off.',
          'For Work or Training, select the Location or Project where the work took place.',
          'If you are on an hourly rate, enter the number of hours worked. Leave blank if you are paid a day rate.',
          'Optionally, link the record to a specific Contract Assignment if one has been scheduled for you.',
          'Add any notes relevant to the day, then click Submit.',
          'Your record will show as Pending in your attendance history until an administrator approves or rejects it.',
        ],
        fields: [
          { name: 'Date', required: true, description: 'The date the attendance record applies to. Cannot be in the future.' },
          { name: 'Type', required: true, description: 'Work / Training / Sick / Holiday / Leave / Off.' },
          { name: 'Location / Project', required: 'Work & Training', description: 'The site or project where work took place.' },
          { name: 'Hours Worked', required: false, description: 'Required for hourly-rate staff. Leave blank if you are on a day rate.' },
          { name: 'Contract Assignment', required: false, description: 'Links this record to a scheduled assignment for reporting purposes.' },
          { name: 'Notes', required: false, description: 'Any additional context — useful for sick days or unusual circumstances.' },
        ],
        notes: [
          'You can only submit one record per date per location/project.',
          'Once a record is approved it is locked — contact your administrator if a correction is needed.',
          'Holiday submissions trigger holiday accrual automatically once approved.',
        ],
      },
      {
        id: 'attendance-history',
        title: 'Viewing Your Attendance History',
        badge: 'Employee / Subcontractor',
        description: 'You can see all your own past and pending attendance records in the Attendance section.',
        steps: [
          'Go to Attendance (/daily or /weekly) — your records are filtered to show only yours.',
          'Pending records have an amber indicator. Approved records are green. Rejected records are red.',
          'You cannot edit a submitted record — if you made a mistake, contact your administrator.',
        ],
        notes: [
          'Only your own records are visible to you. Administrators can see everyone.',
        ],
      },
      {
        id: 'attendance-statuses',
        title: 'Attendance Statuses Explained',
        badge: 'All roles',
        description: 'Every attendance record moves through an approval workflow with three possible statuses.',
        fields: [
          { name: 'Pending', required: '', description: 'Submitted and awaiting review. The record is not yet counted in payroll or holiday balances.' },
          { name: 'Approved', required: '', description: 'Confirmed by an administrator. Feeds directly into payroll calculations and holiday accrual.' },
          { name: 'Rejected', required: '', description: 'Declined by an administrator. You may resubmit with corrections if required.' },
        ],
        notes: [],
      },
      {
        id: 'daily-attendance',
        title: 'Daily Attendance View',
        badge: 'Admin',
        description: 'View every attendance record submitted for a single date and approve or reject them individually.',
        steps: [
          'Go to Attendance → Daily (/daily) — defaults to today.',
          'Use the date picker to navigate to any date.',
          'Each row shows the person\'s name, attendance type, location, hours worked, and current approval status.',
          'Click Approve or Reject on individual Pending records. Add a rejection reason when rejecting.',
        ],
        notes: [],
      },
      {
        id: 'weekly-attendance',
        title: 'Weekly Attendance & Payroll',
        badge: 'Admin / Accountant',
        description: 'The weekly view combines employee attendance and subcontractor payments into a single payroll summary for a tax week. UK tax weeks run Saturday–Friday.',
        steps: [
          'Go to Payroll (/payroll) or navigate directly to /weekly.',
          'Use the Previous / Next arrows to move between tax weeks.',
          'Each row represents one employee or subcontractor with a cell per calendar day.',
          'Employee pay columns show: daily hours × hourly rate. Day-rate staff show a flat daily amount.',
          'Subcontractor payments pull automatically from KashFlow purchase invoices paid within that week — shown with a cyan Purchase badge.',
          'Use Bulk Approve to approve all Pending records for the current week in one click.',
          'The Management View (/weekly-management) shows headcount and activity without revealing payment amounts.',
        ],
        notes: [
          'Subcontractors only appear in the payroll view if they have a valid HMRC Verification Number on their supplier record.',
          'Tax weeks follow the UK April–March tax year. April is the start of tax month 1.',
        ],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  //  HOLIDAYS
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'holidays',
    title: 'Holidays',
    icon: 'bi-umbrella',
    colorClass: 'text-sky-600 dark:text-sky-400',
    bgClass: 'bg-sky-500',
    borderClass: 'border-sky-500',
    articles: [
      {
        id: 'requesting-holiday',
        title: 'How Holiday Works',
        badge: 'Employee',
        description: 'Holiday is submitted as an attendance record with type "Holiday". It does not go through a separate holiday request system — submit it the same way as any other attendance day.',
        steps: [
          'Go to Attendance → Submit (/attendance/submit).',
          'Select the date(s) you are taking as holiday.',
          'Set the attendance type to Holiday.',
          'Submit — the record will be Pending until your administrator approves it.',
          'Once approved, your holiday balance is updated automatically.',
        ],
        notes: [
          'You must submit one attendance record per calendar day of leave.',
          'Your administrator must approve the submission before your balance is adjusted.',
        ],
      },
      {
        id: 'holiday-balance',
        title: 'Your Holiday Balance',
        badge: 'Employee',
        description: 'Your current holiday balance and full history are available under the HR / Holidays section.',
        steps: [
          'Go to HR → Holidays or navigate to /employeeHolidays.',
          'Your balance shows total entitlement, days taken, and days remaining for the current tax year.',
          'The history tab lists every approved holiday record that contributed to the balance.',
        ],
        notes: [
          'Holiday entitlement is based on the Holiday Policy set on your employee record by your administrator.',
          'The UK tax year runs April–March. Entitlement resets each April.',
          'Unused days may be carried over up to the carryover limit defined in your holiday policy.',
        ],
      },
      {
        id: 'holiday-accrual',
        title: 'Holiday Accrual (Admin / HR)',
        badge: 'Admin',
        description: 'Holiday balances are managed per employee and updated automatically when attendance records of type Holiday are approved.',
        steps: [
          'Configure each employee\'s holiday entitlement via their Holiday Policy field.',
          'Set the entitlement days, carryover limit, and accrual method on the employee record.',
          'When an attendance record with type Holiday is approved, the accrual service runs automatically.',
          'View an employee\'s full balance and history under HR → Holidays.',
        ],
        notes: [
          'Holiday accrual is idempotent — approving the same record twice does not double-count.',
        ],
      },
    ],
  },
  // ─────────────────────────────────────────────────────────────────────────
  //  SUBCONTRACTOR PORTAL
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'subcontractor-portal',
    title: 'Subcontractor Portal',
    icon: 'bi-person-gear',
    colorClass: 'text-amber-600 dark:text-amber-400',
    bgClass: 'bg-amber-500',
    borderClass: 'border-amber-500',
    articles: [
      {
        id: 'subcontractor-access',
        title: 'What Subcontractors Can Access',
        badge: 'Subcontractor',
        description: 'Your account gives you access to your own records only. You can submit attendance, view your invoices from us, check your CIS deduction details, and manage vehicles assigned to you.',
        fields: [
          { name: 'Attendance', required: '', description: 'Submit, view, and track approval of your own attendance records.' },
          { name: 'Supplier Record', required: '', description: 'View your own supplier profile including contact details, CIS rate, and VAT number.' },
          { name: 'Purchase Invoices', required: '', description: 'View all purchase invoices we have raised against your supplier account.' },
          { name: 'CIS Returns', required: '', description: 'View your own CIS deduction summary for any tax month.' },
          { name: 'Vehicles', required: '', description: 'View and log mileage/fuel for any vehicle assigned to you.' },
        ],
        notes: [
          'You can only see your own records — you cannot view other subcontractors\' data.',
          'If your account is not linked to a supplier record, contact your administrator.',
        ],
      },
      {
        id: 'subcontractor-cis',
        title: 'Your CIS Deductions',
        badge: 'Subcontractor',
        description: 'View the CIS deductions applied to your payments for any tax month or full tax year.',
        steps: [
          'Go to CIS (/construction-industry-scheme) for the department landing page.',
          'View your monthly return: /CIS/returns/:uuid/:year/:month — e.g. month 1 = April.',
          'View your full yearly return: /CIS/returns/:uuid/yearly/:year.',
          'Each return shows: gross payment, labour, materials, CIS deduction rate, amount deducted, and net received.',
        ],
        notes: [
          'UK tax months run April–March. April is tax month 1, March is tax month 12.',
          'Your CIS rate (0%, 20%, or 30%) is set by your contractor based on your HMRC registration status.',
          'The deducted amount is paid directly to HMRC on your behalf.',
        ],
      },
      {
        id: 'subcontractor-invoices',
        title: 'Your Purchase Invoices',
        badge: 'Subcontractor',
        description: 'View all purchase invoices raised by the company against your account.',
        steps: [
          'Go to Finance → Purchases or navigate to /purchases.',
          'Only invoices linked to your supplier account are shown.',
          'Each invoice shows the gross amount, CIS deduction, net paid, line items, and payment status.',
        ],
        notes: [
          'Invoices are synced from KashFlow. If an invoice is missing, check with your contractor or allow time for the next sync.',
        ],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  //  CLIENT PORTAL
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'client-portal',
    title: 'Client Portal',
    icon: 'bi-briefcase',
    colorClass: 'text-cyan-600 dark:text-cyan-400',
    bgClass: 'bg-cyan-500',
    borderClass: 'border-cyan-500',
    articles: [
      {
        id: 'client-access',
        title: 'What Clients Can Access',
        badge: 'Client',
        description: 'As a client you have read-only access to records associated with your customer account: your customer profile, invoices raised against you, quotes, and any projects linked to your account.',
        fields: [
          { name: 'Customer Record', required: '', description: 'Your own customer profile including contact details and outstanding balance.' },
          { name: 'Invoices', required: '', description: 'All invoices raised against your account — including status (Outstanding / Paid / Overdue / Credited).' },
          { name: 'Quotes', required: '', description: 'All quotes sent to your account.' },
          { name: 'Projects', required: '', description: 'Any KashFlow projects linked to your customer account.' },
        ],
        notes: [
          'You can only see records belonging to your own customer account.',
          'If your account is not linked to a customer record, contact your administrator.',
          'Data is synced from KashFlow — updates made there will appear after the next automatic sync (typically within one hour).',
        ],
      },
      {
        id: 'client-invoices',
        title: 'Viewing Your Invoices',
        badge: 'Client',
        description: 'See all invoices raised to your account, including outstanding balances and payment history.',
        steps: [
          'Go to Finance → Invoices or navigate to /invoices.',
          'Only invoices belonging to your customer account are shown.',
          'Each invoice shows the invoice number, date, gross amount, amount paid, outstanding balance, and current status.',
          'Click an invoice to view the full breakdown including line items.',
        ],
        notes: [
          'Invoice statuses: Draft, Sent, Paid, Overdue, Credited, Void. Overdue invoices have a due date that has passed with an outstanding balance.',
        ],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  //  CIS
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'cis',
    title: 'CIS — Construction Industry Scheme',
    icon: 'bi-building',
    colorClass: 'text-orange-600 dark:text-orange-400',
    bgClass: 'bg-orange-500',
    borderClass: 'border-orange-500',
    articles: [
      {
        id: 'what-is-cis',
        title: 'What is CIS?',
        badge: 'Accountant / Admin / HMRC',
        description: 'The Construction Industry Scheme (CIS) is a HMRC scheme where contractors deduct money from their subcontractor payments and pass it to HMRC as advance tax. The deduction is an advance on the subcontractor\'s Income Tax and National Insurance.',
        fields: [
          { name: 'Gross Amount', required: '', description: 'Labour + Materials. The total earned before any CIS deduction.' },
          { name: 'CIS Deduction', required: '', description: 'Labour × CIS rate. Rates are 0% (gross status), 20% (registered), or 30% (unregistered/unverified).' },
          { name: 'Net Payment', required: '', description: 'Gross − CIS Deduction. This is the amount actually paid to the subcontractor.' },
        ],
        notes: [
          'Materials are excluded from the CIS deduction calculation — only labour is subject to deduction.',
          'WHT rates are normalised automatically from both whole-number (20) and decimal (0.2) formats held in KashFlow.',
          'The deducted amount is remitted to HMRC by the contractor as part of their monthly CIS return.',
        ],
      },
      {
        id: 'cis-rates',
        title: 'CIS Deduction Rates',
        badge: 'Accountant / Admin',
        description: 'Each subcontractor\'s CIS deduction rate is stored on their supplier record and must reflect their HMRC verification status.',
        fields: [
          { name: '0% (Gross Status)', required: '', description: 'HMRC has granted the subcontractor gross payment status. No deduction is made.' },
          { name: '20% (Registered)', required: '', description: 'The subcontractor is registered with HMRC and has been verified.' },
          { name: '30% (Unregistered / Unverified)', required: '', description: 'The subcontractor is not registered or could not be verified with HMRC. Higher deduction applies.' },
        ],
        notes: [
          'To change a subcontractor\'s CIS rate, edit their Supplier record in the Finance or Subcontractors section.',
          'The CIS Number field should hold the subcontractor\'s HMRC-verified CIS Unique Taxpayer Reference (UTR).',
          'Changes to CIS rates made in this system are preserved during KashFlow syncs — they are protected fields.',
        ],
      },
      {
        id: 'cis-dashboard',
        title: 'CIS Monthly Dashboard',
        badge: 'Accountant / Admin / HMRC',
        description: 'The CIS dashboard shows deduction summaries broken down by subcontractor for any tax month.',
        steps: [
          'Go to CIS (/construction-industry-scheme).',
          'Navigate to a monthly summary: /CIS/Dashboard/:year/:month — e.g. /CIS/Dashboard/2026/1 for April 2025 (month 1 of the 2025/26 tax year).',
          'Each row shows: subcontractor name, gross amount, labour portion, materials portion, CIS rate, deduction taken, and net paid.',
          'Nominal codes are mapped automatically from KashFlow to identify labour lines, materials lines, and CIS deduction lines.',
        ],
        notes: [
          'The UK tax year runs April–March. April is tax month 1, March is tax month 12.',
          'Only purchase invoices from suppliers with Apply Withholding Tax enabled are included in the CIS dashboard.',
        ],
      },
      {
        id: 'cis-returns',
        title: 'Monthly & Yearly Returns',
        badge: 'Accountant / Admin',
        description: 'Generate CIS return summaries for any tax month or full tax year for submission to HMRC.',
        steps: [
          'Go to CIS → Returns (/CIS/returns/form) and select the tax year and month to view.',
          'Monthly return for all subcontractors: /CIS/returns/all/:year/:month.',
          'Yearly summary for all subcontractors: /CIS/returns/all/:year — shows all 12 months in one view.',
          'Individual subcontractor yearly return: /CIS/returns/:uuid/yearly/:year.',
          'Individual subcontractor monthly return: /CIS/returns/:uuid/:year/:month.',
          'Each return aggregates all purchases from CIS subcontractors within the period, grouped by subcontractor.',
        ],
        notes: [
          'Returns are generated from synced KashFlow data. Ensure the sync is up to date before filing.',
          'Subcontractors can view their own individual monthly and yearly returns.',
        ],
      },
      {
        id: 'cis-subcontractor-setup',
        title: 'Adding a Supplier as a CIS Subcontractor',
        badge: 'Admin',
        description: 'The subcontractor list on the Create Assignment form only shows suppliers who have been set up for CIS withholding in KashFlow. If a supplier is missing from the list, follow these steps to enable them.',
        steps: [
          'Log in to KashFlow at https://app.kashflow.com.',
          'In the top navigation, go to Contacts → Suppliers.',
          'Search for the supplier and click their name to open their record.',
          'Click the Edit button (pencil icon) to enter edit mode.',
          'Scroll down to the Payment & Tax section.',
          'Tick the checkbox labelled "Apply Withholding Tax / CIS".',
          'In the Withholding Tax Rate field, enter the correct CIS deduction rate: 0 for gross status, 20 for registered, or 30 for unverified.',
          'In the Withholding Tax References section, click Add Reference. Set the Name to "Verification Number" and enter the subcontractor\'s HMRC CIS verification number in the Value field.',
          'Click Save to apply the changes.',
          'Return to this system and wait up to one hour for the next automatic sync, or ask your administrator to trigger a manual sync from the hcs-sync dashboard.',
          'Once synced, the supplier will appear in the Assigned Subcontractors list on the Create Assignment form.',
        ],
        notes: [
          'Only suppliers with a Withholding Tax Rate set (0%, 20%, or 30%) in KashFlow appear in the subcontractor list.',
          'The CIS rate set here is preserved during syncs — it will not be overwritten by KashFlow.',
          'If the supplier does not yet exist in KashFlow, create them under Contacts → Suppliers before following the steps above.',
          'Gross status (0%) subcontractors must still have a Withholding Tax Rate of 0 entered — the field must be present for the supplier to appear in the list.',
        ],
      },
    ],
  },
  // ─────────────────────────────────────────────────────────────────────────
  //  FLEET
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'fleet',
    title: 'Fleet & Vehicles',
    icon: 'bi-truck',
    colorClass: 'text-indigo-600 dark:text-indigo-400',
    bgClass: 'bg-indigo-500',
    borderClass: 'border-indigo-500',
    articles: [
      {
        id: 'vehicle-my-vehicle',
        title: 'Viewing a Vehicle Assigned to You',
        badge: 'Employee / Subcontractor',
        description: 'If a company vehicle is assigned to your account, you can view its details and log fuel and mileage from your own dashboard.',
        steps: [
          'Go to Maintenance → Vehicles or navigate to /vehicles.',
          'Only vehicles assigned to you are shown.',
          'Click the vehicle to see its full detail: registration, make, model, compliance dates, and service history.',
          'Use the Fuel Logs and Mileage Logs tabs to record trips and fill-ups.',
        ],
        notes: [
          'If you expect to see a vehicle but it is not listed, contact your administrator — the vehicle may not yet be assigned to your account.',
        ],
      },
      {
        id: 'vehicle-overview',
        title: 'Managing the Fleet',
        badge: 'Admin',
        description: 'Admin users can create, edit, and manage all company vehicles. Each vehicle is assigned to one person (employee or subcontractor).',
        steps: [
          'Go to Maintenance → Vehicles or navigate to /vehicles.',
          'Click Add Vehicle to create a new record.',
          'Enter the registration, make, model, fuel type, and compliance dates.',
          'Assign the vehicle to either an employee or a subcontractor — not both.',
          'Set the availability status to reflect the vehicle\'s current state.',
        ],
        fields: [
          { name: 'Registration Number', required: true, description: 'Must be unique. Stored in uppercase automatically.' },
          { name: 'Make / Model', required: true, description: 'Manufacturer and model name. Shown as "REG – Make Model" throughout the system.' },
          { name: 'MOT Expiry Date', required: false, description: 'Triggers a compliance task when within 30 days or already expired.' },
          { name: 'Insurance Expiry Date', required: false, description: 'Same automatic alerting as MOT.' },
          { name: 'Road Tax Expiry Date', required: false, description: 'Same automatic alerting as MOT.' },
          { name: 'Assigned To', required: true, description: 'Assign to either an employee or a subcontractor. Cannot be both.' },
          { name: 'Availability Status', required: false, description: 'Available / In Use / Under Maintenance / Out of Service / Disposed.' },
        ],
        notes: [
          'Compliance alerts are checked daily. Any date within 30 days of expiry creates tasks for all admin users automatically.',
        ],
      },
      {
        id: 'mileage-logs',
        title: 'Mileage Logs',
        badge: 'Admin / Employee / Subcontractor',
        description: 'Record per-trip odometer readings against a vehicle. Distance and HMRC mileage claim amounts are calculated automatically.',
        steps: [
          'Open a vehicle record and click the Mileage Logs tab.',
          'Click Add Mileage Log and enter the trip start and end odometer readings.',
          'Select the date and the trip purpose.',
          'If the trip is claimable, mark it as such and enter the HMRC pence-per-mile rate.',
          'The distance and reimbursement amount are calculated automatically.',
        ],
        fields: [
          { name: 'Start / End Mileage', required: true, description: 'Odometer readings. End must be greater than or equal to start.' },
          { name: 'Trip Purpose', required: false, description: 'Business / Commute / Personal / Site Visit / Delivery / Client Meeting / Training / Other.' },
          { name: 'Claimable', required: false, description: 'Whether the trip qualifies for an HMRC mileage reimbursement.' },
          { name: 'HMRC Rate', required: false, description: 'Pence per mile — e.g. 45 for 45p/mile.' },
        ],
        notes: [
          'HMRC advisory rate for cars is 45p/mile for the first 10,000 miles in a tax year, then 25p/mile.',
        ],
      },
      {
        id: 'fuel-logs',
        title: 'Fuel Logs',
        badge: 'Admin / Employee / Subcontractor',
        description: 'Track every fuel fill-up for cost monitoring and consumption analysis.',
        steps: [
          'Open a vehicle record and click the Fuel Logs tab.',
          'Click Add Fuel Log and enter the date, fuel type, volume in litres, and total cost.',
          'Enter the current odometer reading to enable consumption calculations.',
        ],
        fields: [
          { name: 'Fuel Type', required: true, description: 'Petrol / Diesel / Electric / Hybrid / LPG / Hydrogen / AdBlue.' },
          { name: 'Litres', required: true, description: 'Volume of fuel added to the tank.' },
          { name: 'Total Cost', required: true, description: 'Amount paid at the pump (or for the charge).' },
          { name: 'Full Tank', required: false, description: 'Whether this was a full fill-up — used to improve consumption calculations.' },
          { name: 'Payment Method', required: false, description: 'Fuel Card / Company Card / Cash / Personal Expense / Other.' },
        ],
        notes: [],
      },
      {
        id: 'service-records',
        title: 'Service Records',
        badge: 'Admin',
        description: 'Log all maintenance and servicing events for a vehicle — MOTs, oil changes, tyre replacements, bodywork, and more.',
        steps: [
          'Open a vehicle record and click the Service Records tab.',
          'Click Add Service Record and select the service type.',
          'Enter the date and any advisory notes from the testing station (for MOTs).',
          'Parts replaced can be listed individually with quantities and costs.',
          'Setting a Next Service Due Date here automatically updates the parent vehicle record.',
        ],
        fields: [
          { name: 'Service Type', required: true, description: 'Full / Interim / Major Service, MOT, Tyre Replacement, Oil Change, Brake Service, Bodywork Repair, Diagnostic, and more.' },
          { name: 'Status', required: false, description: 'Scheduled / In Progress / Completed / Cancelled.' },
          { name: 'Passed', required: false, description: 'MOT only — whether the vehicle passed the test.' },
          { name: 'Advisories', required: false, description: 'MOT advisory notes from the testing station.' },
          { name: 'Next Service Due Date', required: false, description: 'Propagates to the parent vehicle record when saved.' },
        ],
        notes: [],
      },
      {
        id: 'compliance-alerts',
        title: 'Compliance Alerts',
        badge: 'Admin',
        description: 'The system automatically monitors MOT, insurance, and road tax expiry dates across all vehicles and creates tasks when action is needed.',
        steps: [
          'The compliance check runs automatically every 24 hours.',
          'Any compliance date that is expired or within 30 days of expiry triggers task creation.',
          'Tasks are assigned to all admin users and labelled [EXPIRED] or [EXPIRING] with the vehicle registration and compliance type.',
          'View and action these tasks from the dashboard task strip.',
          'Once the vehicle\'s compliance date is updated, the alert task will no longer recur.',
        ],
        notes: [
          'Compliance check is idempotent — it will not create duplicate tasks if one already exists for the same vehicle and event.',
        ],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  //  HR & PEOPLE
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'hr',
    title: 'HR & People',
    icon: 'bi-people',
    colorClass: 'text-pink-600 dark:text-pink-400',
    bgClass: 'bg-pink-500',
    borderClass: 'border-pink-500',
    articles: [
      {
        id: 'employees',
        title: 'Employee Records',
        badge: 'Admin',
        description: 'Employee records hold all HR-relevant information: personal details, pay rates, contract terms, IR35 status, and holiday entitlement.',
        steps: [
          'Go to HR → Employees or navigate to /employees.',
          'Click Add Employee to create a new record.',
          'Set the employee status to Active — only active employees appear in attendance and payroll views.',
          'Enter pay rates: set the Defined Rate (hourly/daily/weekly/monthly/yearly) and the corresponding amount.',
          'Configure the Holiday Policy: entitlement days, carryover limit, and accrual method.',
          'Set Contract Terms: hours per week, working days, notice period, and (for fixed-term) start and end dates.',
          'If the employee is an off-payroll worker (IR35), enable the IR35 flag and link their supplier record.',
        ],
        fields: [
          { name: 'Status', required: true, description: 'Active / Inactive. Only active employees appear in attendance and payroll.' },
          { name: 'Hourly Rate', required: false, description: 'Used to calculate weekly pay from approved attendance hours.' },
          { name: 'Defined Rate', required: false, description: 'Hourly / Daily / Weekly / Monthly / Yearly.' },
          { name: 'IR35', required: false, description: 'Flag for off-payroll workers. When set, links this employee record to a supplier.' },
          { name: 'Holiday Policy', required: false, description: 'Entitlement days, carryover limit, and accrual method for the tax year.' },
          { name: 'Contract Terms', required: false, description: 'Hours per week, working days, notice period, start and end date.' },
        ],
        notes: [
          'Inactive employees are hidden from attendance, payroll, and assignment views.',
        ],
      },
      {
        id: 'contracts-assignments',
        title: 'Contracts & Assignments',
        badge: 'Admin',
        description: 'Contracts represent site jobs. Assignments schedule employees and subcontractors to a contract for a specific week.',
        steps: [
          'Create a Contract under Management → Contracts. Optionally link it to a KashFlow project or quote.',
          'Set the Contract Status (Planned / In Progress / Completed) and add a description, site location, and dates.',
          'Create an Assignment under the contract by clicking Add Assignment.',
          'Set the Week Start date (Monday) and add the employees and subcontractors scheduled for that week.',
          'Enter estimated hours for the assignment block.',
          'When employees submit attendance, they can optionally link to the relevant assignment for reporting.',
        ],
        fields: [
          { name: 'Contract Status', required: false, description: 'Planned / In Progress / Completed.' },
          { name: 'Week Start', required: true, description: 'The Monday of the week this assignment covers.' },
          { name: 'Assigned Employees', required: false, description: 'Internal employees scheduled to work this week.' },
          { name: 'Assigned Subcontractors', required: false, description: 'Subcontractors scheduled for this week.' },
          { name: 'Estimated Hours', required: false, description: 'Total planned hours for this assignment block.' },
        ],
        notes: [],
      },
      {
        id: 'tasks',
        title: 'Tasks',
        badge: 'Admin',
        description: 'Tasks are to-do items for admin users. They can be one-off or set to recur on a schedule. Vehicle compliance tasks are auto-created by the system.',
        steps: [
          'Create a task from the Dashboard Quick Add form, or go to HR → Tasks.',
          'Set a title, description, and optional due date.',
          'Set recurrence: None / Daily / Weekly / Monthly. When a recurring task is marked complete, the next instance is automatically created.',
          'Optionally link to a Contract for project context.',
          'Mark tasks complete from the dashboard card or the task detail page.',
        ],
        fields: [
          { name: 'Due Date', required: 'For recurring', description: 'Required when recurrence is set. Optional for one-off tasks.' },
          { name: 'Recurrence', required: false, description: 'None / Daily / Weekly / Monthly.' },
          { name: 'Contract', required: false, description: 'Optional link to a related contract for project tracking.' },
        ],
        notes: [
          'Vehicle compliance tasks ([EXPIRING] and [EXPIRED]) are auto-generated — do not create them manually.',
          'System-generated tasks will not be re-created if you have already resolved the underlying compliance issue.',
        ],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  //  FINANCE
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'finance',
    title: 'Finance & KashFlow',
    icon: 'bi-wallet2',
    colorClass: 'text-teal-600 dark:text-teal-400',
    bgClass: 'bg-teal-500',
    borderClass: 'border-teal-500',
    articles: [
      {
        id: 'kashflow-sync',
        title: 'How Financial Data Gets Here',
        badge: 'Accountant / Admin',
        description: 'All financial data — customers, suppliers, invoices, purchases, projects, quotes, and nominals — is synced automatically from KashFlow by a background sync service. There is nothing to configure manually.',
        steps: [
          'Incremental syncs run every hour, picking up new and changed records.',
          'A full refresh runs every 24 hours to ensure nothing is missed.',
          'All data shown in Finance, CIS, and Payroll comes from this sync.',
          'To check when data was last updated, go to the KashFlow Sync Status dashboard.',
        ],
        notes: [
          'The sync is read-only — it never pushes data back to KashFlow.',
          'Some fields (e.g. CIS deduction rates, withholding tax flags) that you set in this system are protected and will not be overwritten by the sync.',
        ],
      },
      {
        id: 'invoices',
        title: 'Invoices',
        badge: 'Accountant / Admin / Client',
        description: 'Invoices represent amounts your customers owe to you. All invoice data comes from KashFlow.',
        steps: [
          'Go to Finance → Invoices or navigate to /invoices.',
          'Use the search box and filters to find invoices by customer, date, status, or amount.',
          'Click any invoice to view the full detail: line items, payment lines, and a running total.',
          'Clients can only see their own invoices.',
        ],
        fields: [
          { name: 'Status', required: '', description: 'Draft / Sent / Paid / Overdue / Credited / Void. Overdue = due date passed with outstanding balance.' },
          { name: 'Gross Amount', required: '', description: 'Total invoice value including VAT.' },
          { name: 'Amount Paid', required: '', description: 'Total payments received against this invoice.' },
          { name: 'Due Amount', required: '', description: 'Gross Amount − Amount Paid. The outstanding balance.' },
          { name: 'Due Date', required: '', description: 'Payment deadline. Used to determine if the invoice is overdue.' },
        ],
        notes: [],
      },
      {
        id: 'purchases',
        title: 'Purchases',
        badge: 'Accountant / Admin / Subcontractor',
        description: 'Purchases are amounts the company owes to suppliers. For CIS subcontractors, purchase invoices drive the payroll and CIS deduction calculations.',
        steps: [
          'Go to Finance → Purchases or navigate to /purchases.',
          'Filter by supplier, date range, status, or amount.',
          'Click a purchase to see line items, payment lines, and which nominal codes each line is attributed to.',
          'Subcontractors can only see their own purchases.',
        ],
        notes: [
          'Purchase invoices from CIS-registered suppliers (with Apply Withholding Tax enabled) automatically appear in the payroll and CIS views.',
        ],
      },
      {
        id: 'suppliers',
        title: 'Suppliers',
        badge: 'Accountant / Admin',
        description: 'Supplier records hold contact information and CIS/VAT settings. CIS fields are editable here and are protected from being overwritten during KashFlow syncs.',
        steps: [
          'Go to Finance → Suppliers or navigate to /suppliers.',
          'Click a supplier to view or edit their record.',
          'To configure CIS for a subcontractor: set Apply Withholding Tax, enter their CIS Number (UTR), and set the CIS Rate (0%, 20%, or 30%).',
          'Changes to CIS fields are preserved across KashFlow syncs.',
        ],
        fields: [
          { name: 'Apply Withholding Tax', required: false, description: 'Enable to include this supplier in CIS deduction calculations.' },
          { name: 'CIS Number', required: false, description: 'The subcontractor\'s HMRC-verified Unique Taxpayer Reference (UTR).' },
          { name: 'CIS Rate', required: false, description: '0 (gross status), 0.2 (20% registered), or 0.3 (30% unregistered).' },
          { name: 'HMRC Verification Number', required: false, description: 'Required for subcontractors to appear in the payroll view.' },
        ],
        notes: [
          'CIS fields on supplier records are protected — they will not be overwritten during KashFlow syncs.',
        ],
      },
      {
        id: 'projects-quotes',
        title: 'Projects & Quotes',
        badge: 'Accountant / Admin / Client',
        description: 'KashFlow projects and quotes provide a link between financial records and the work carried out on site.',
        steps: [
          'View all KashFlow projects under Finance → Projects.',
          'View all quotes under Finance → Quotes.',
          'Link a KashFlow project or quote to an internal Contract by editing the Contract record under Management.',
          'Clients can see projects and quotes associated with their own customer account.',
        ],
        notes: [
          'Active projects appear in the weekly attendance view as a reference list for location selection.',
        ],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  //  DOCUMENTS
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'documents',
    title: 'Documents',
    icon: 'bi-file-earmark-text',
    colorClass: 'text-rose-600 dark:text-rose-400',
    bgClass: 'bg-rose-500',
    borderClass: 'border-rose-500',
    articles: [
      {
        id: 'paperless-overview',
        title: 'Document Ingestion from Paperless-ngx',
        badge: 'Admin',
        description: 'The Documents section pulls scanned and OCR\'d documents from Paperless-ngx — an external document management system — and makes them searchable within HCS.',
        steps: [
          'Documents are scanned, uploaded, and processed by OCR within Paperless-ngx separately.',
          'In HCS, go to Documents (/paperless) and trigger an ingest to pull the latest batch.',
          'Ingested documents are stored as searchable records and indexed by content, correspondent, and tags.',
          'Documents can be linked to KashFlow purchase records for reconciliation.',
        ],
        notes: [
          'Paperless-ngx runs as a separate service and must be configured by your system administrator.',
          'Ingestion is incremental — it only pulls documents not previously imported.',
        ],
      },
      {
        id: 'document-linking',
        title: 'Linking Documents to Purchases',
        badge: 'Admin',
        description: 'OCR\'d documents (such as supplier invoices and receipts) can be linked to their corresponding KashFlow purchase records for a complete audit trail.',
        steps: [
          'Open a document from the Documents list.',
          'Use the Link to Purchase field to search for and attach the matching purchase record.',
          'Once linked, the document will appear on the purchase record\'s detail page.',
        ],
        notes: [
          'The OCR content is searchable — use keywords from the supplier name, amount, or invoice number to find the right purchase.',
        ],
      },
      {
        id: 'paperless-kashflow-draft',
        title: 'Sending an OCR Document to KashFlow',
        badge: 'Admin',
        description: 'Once a document is ingested from Paperless-ngx, you can use the OCR-extracted data to generate a purchase invoice draft and send it directly to KashFlow — avoiding manual data entry.',
        steps: [
          'Go to Documents → OCR Documents (/paperless/ocr).',
          'Click on a document to open it.',
          'Click Create Draft to navigate to the draft form (/paperless/ocr/:id/draft).',
          'The form pre-populates with data extracted by OCR: supplier name, amounts, invoice date, and line items.',
          'Review and correct any fields where the OCR may have misread the document.',
          'Use the supplier search to find and select the matching KashFlow supplier — this links the purchase to the correct supplier account.',
          'When satisfied, click Send to KashFlow. The draft is submitted as a new purchase invoice.',
          'A success banner will show the new KashFlow purchase number created.',
        ],
        notes: [
          'OCR accuracy depends on scan quality — always review extracted values before sending.',
          'Sending a draft to KashFlow is irreversible — a new purchase record will be created and will appear in the system after the next sync.',
          'Supplier search queries KashFlow directly for up-to-date supplier names and IDs.',
        ],
      },
      {
        id: 'file-attachments',
        title: 'Attaching Files to Records',
        badge: 'Admin',
        description: 'Files (images, PDFs, and Word documents) can be uploaded directly against any record that supports attachments — employees, vehicles, suppliers, and others.',
        steps: [
          'Open any record that supports file attachments — look for a Documents section or Upload button on the detail page.',
          'Click Upload Documents to open the upload form for that record.',
          'Select up to 10 files. Allowed types: JPEG, PNG, PDF, DOC, DOCX. Maximum size: 5 MB per file.',
          'Click Upload. Files are saved immediately and appear in the Documents section of the record.',
          'To view a file, click its name — images and PDFs open in the browser; other formats download automatically.',
          'To download a file without opening it, use the Download link beside the file.',
          'To delete a file, click the Delete button beside the file and confirm.',
        ],
        fields: [
          { name: 'Allowed Types', required: '', description: 'JPEG, JPG, PNG, PDF, DOC, DOCX.' },
          { name: 'Max File Size', required: '', description: '5 MB per file.' },
          { name: 'Max Files Per Upload', required: '', description: '10 files per upload batch.' },
        ],
        notes: [
          'Files are stored on the server under public/<model>/<uuid>/.',
          'Deleting a record does not automatically remove its attached files — contact your administrator to clean up orphaned files.',
        ],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  //  ADMIN
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'admin',
    title: 'Administration',
    icon: 'bi-shield-check',
    colorClass: 'text-gray-600 dark:text-gray-400',
    bgClass: 'bg-gray-500',
    borderClass: 'border-gray-500',
    articles: [
      {
        id: 'user-management',
        title: 'Managing Users',
        badge: 'Admin',
        description: 'Admin users can create, edit, and deactivate user accounts and set their roles, linked entities, and custom permissions.',
        steps: [
          'Go to Admin → Users or navigate to /users.',
          'Click Add User to create a new account, or click an existing user to edit them.',
          'Set the role (admin / accountant / employee / subcontractor / client / hmrc / none).',
          'Link the user to their corresponding record: employee, supplier (subcontractor), or customer (client).',
          'If the user needs access beyond their standard role, use the Custom Permissions panel to grant specific model, department, or route access.',
          'To resend the email verification link, use the Resend Verification button on the user record.',
        ],
        fields: [
          { name: 'Role', required: true, description: 'Determines all page and data access. See the Your Role & Access section.' },
          { name: 'Employee Link', required: 'Employee role', description: 'Links the user account to an employee record for attendance and payroll data scoping.' },
          { name: 'Subcontractor Link', required: 'Subcontractor role', description: 'Links to a supplier record for purchase invoices, CIS, and vehicles.' },
          { name: 'Client Link', required: 'Client role', description: 'Links to a customer record for invoices, quotes, and projects.' },
        ],
        notes: [
          'A user with no role assigned (role = none) cannot access any data until their role is set.',
          'Custom permissions can extend or override standard RBAC rules — use with care.',
        ],
      },
      {
        id: 'bulk-import',
        title: 'Bulk Imports',
        badge: 'Admin',
        description: 'Import multiple employee or subcontractor records at once via CSV upload.',
        steps: [
          'Go to Admin → Bulk Import.',
          'Download the CSV template for the record type you want to import.',
          'Fill in the template with your data and upload the file.',
          'Review the validation summary — rows with errors are highlighted with the reason for rejection.',
          'Confirm to import the valid rows.',
        ],
        notes: [
          'Duplicate records (same name or registration) are flagged and skipped — they will not create duplicates.',
          'Existing records are not updated by bulk import — it is for new records only.',
        ],
      },
      {
        id: 'system-status',
        title: 'System Status & Logs',
        badge: 'Admin',
        description: 'Monitor the health of all connected services and manage the live application log stream.',
        steps: [
          'Go to Admin → System Status to see the current state of MongoDB, KashFlow sync, and the session store.',
          'Go to Admin → Logs (/logs) to view the live application log stream.',
          'Logs are colour-coded by severity: info (blue), warn (amber), error (red).',
          'Use the search box in the log viewer to filter for specific events or error messages.',
          'To download logs, click Download Logs — optionally filter by level using /logs/download?level=error (or info / warn).',
          'To clear the log file, click Clear Logs. This permanently removes the on-disk log — download a copy first if you need to retain the history.',
        ],
        notes: [
          'The log viewer requires WebSocket support in your browser — use a modern browser for the best experience.',
          'Clearing the log only removes the current on-disk file. Previously streamed entries visible in the UI are not affected until you reload.',
        ],
      },
      {
        id: 'settings',
        title: 'Account & Application Settings',
        badge: 'Admin',
        description: 'Personal account settings (password, display name, 2FA) are managed at /user/account. Application-wide settings (SMTP, maintenance mode, session timeout) are configured via environment variables or the setup wizard at /setup.',
        steps: [
          'Go to Account Settings (/user/account) to change your password, display name, or email address.',
          'Two-Factor Authentication is managed from the same account page.',
          'App-wide settings (SMTP server, encryption keys, maintenance mode) are set via environment variables in the deployment configuration.',
          'To run the setup wizard for initial app-wide configuration, navigate to /setup.',
        ],
        notes: [
          'Maintenance mode (MAINTENANCE_MODE env var) returns a 503 page to all non-admin users. Admin users can still access the app.',
        ],
      },
      {
        id: 'custom-permissions',
        title: 'Custom Permissions',
        badge: 'Admin',
        description: 'Custom permissions let you grant an individual user access beyond their standard RBAC role without changing the role itself.',
        steps: [
          'Open the user record you want to adjust (Admin → Users → click the user).',
          'Scroll to the Custom Permissions panel.',
          'Grant model access: specify a model name and the operations to allow — l (list), r (read), c (create), u (update), d (delete).',
          'Grant department access: add a department slug to give access to a department dashboard not normally included in the user\'s role.',
          'Grant route access: add a specific route path to allow access to one page regardless of role.',
          'Save the user record. The permissions take effect immediately on the next page load.',
        ],
        fields: [
          { name: 'Model Permission', required: false, description: 'Specify the model and allowed operations — e.g. grant list and read on invoices.' },
          { name: 'Department Permission', required: false, description: 'Add a department slug (e.g. finance) to grant access to that department dashboard and its tiles.' },
          { name: 'Route Permission', required: false, description: 'Add a specific path (e.g. /CIS/Dashboard/) to allow access to that route regardless of role.' },
        ],
        notes: [
          'Custom permissions extend the standard role — they cannot remove access that the role already grants.',
          'Changes take effect on the user\'s next page load; sessions are re-evaluated per request.',
          'Use custom permissions sparingly — prefer assigning the correct role where possible.',
        ],
      },
      {
        id: 'overview-dashboards',
        title: 'Overview Dashboards',
        badge: 'Admin',
        description: 'Each department has a dedicated overview that summarises key metrics and alerts at a glance. Overviews are accessible from the home page grid and via direct URL.',
        fields: [
          { name: 'Fleet Overview', required: '', description: '/overview/fleet — vehicles with MOT, insurance, or road tax expiring within the selected threshold (default 30 days). Accepts ?days= to adjust the window.' },
          { name: 'Human Resources Overview', required: '', description: '/overview/human — employees with contracts ending within 60 days, holiday balances, and headcount by status. Accepts ?days= for the contract-end window.' },
          { name: 'Finance Overview', required: '', description: '/overview/finance — outstanding invoice totals, overdue invoices, recent payments. Accessible to admin and accountant.' },
          { name: 'Projects Overview', required: '', description: '/overview/projects — active KashFlow projects with linked contracts and assigned subcontractors.' },
          { name: 'Admin Overview', required: '', description: '/overview/admin — open tasks, pending attendance records, user account summary, and system health indicators.' },
          { name: 'Documents Overview', required: '', description: '/overview/documents — unlinked OCR documents and recent Paperless-ngx ingest activity.' },
          { name: 'Subcontractors Overview', required: '', description: '/overview/subcontractors — all CIS subcontractors with rates, HMRC verification numbers, and outstanding purchase totals. Accessible to admin, accountant, and hmrc.' },
        ],
        notes: [
          'Overview tiles only appear on the dashboard home page if your role has access to that department.',
          'The Finance and Subcontractors overviews are also accessible to the accountant and hmrc roles respectively.',
        ],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  //  KEY CONCEPTS & REFERENCE
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'key-concepts',
    title: 'Key Concepts & Reference',
    icon: 'bi-bookmark-check',
    colorClass: 'text-slate-600 dark:text-slate-400',
    bgClass: 'bg-slate-500',
    borderClass: 'border-slate-500',
    articles: [
      {
        id: 'uk-tax-year',
        title: 'UK Tax Year, Months & Weeks',
        badge: 'All roles',
        description: 'The UK tax year runs April–March. Understanding tax months and tax weeks is essential for reading payroll summaries, CIS returns, and holiday balances correctly.',
        fields: [
          { name: 'Tax Year', required: '', description: 'Runs 6 April to 5 April the following year. Referred to by the start year — "2025/26" covers April 2025 to March 2026.' },
          { name: 'Tax Month 1', required: '', description: 'April. Tax Month 12 is March. The monthly count resets every April.' },
          { name: 'Tax Week', required: '', description: 'Runs Saturday–Friday. Tax Week 1 starts the first Saturday on or after 6 April.' },
          { name: 'Holiday Year', required: '', description: 'Aligns with the tax year — entitlement resets each April and any unused days carry over up to the limit set on the employee record.' },
          { name: 'CIS Return Month', required: '', description: 'Filed monthly to HMRC, aligned to tax months. Month 1 (April) is due by 19 May.' },
        ],
        notes: [
          'In URL patterns, :year refers to the tax year start — e.g. /CIS/Dashboard/2025/1 is April 2025 (month 1 of the 2025/26 tax year).',
          'The weekly payroll view uses Saturday–Friday weeks. Week 1 of the tax year always begins in April.',
          'All date arithmetic in the system accounts for UK daylight saving time.',
        ],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  //  UK STATUTORY COMPLIANCE
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'compliance',
    title: 'UK Statutory Compliance',
    icon: 'bi-calendar-check',
    colorClass: 'text-rose-600 dark:text-rose-400',
    bgClass: 'bg-rose-500',
    borderClass: 'border-rose-500',
    articles: [
      {
        id: 'compliance-monthly',
        title: 'Monthly Obligations',
        badge: 'Admin',
        description: 'These tasks fall on or before the 19th of every month (22nd for electronic payment). They recur every tax month without exception.',
        fields: [
          { name: 'CIS300 Return', required: '19th', description: 'File the monthly CIS return covering all payments made to subcontractors in the preceding tax month (6th–5th). Include all subcontractors paid, even at 0% deduction.' },
          { name: 'CIS Deduction Payment', required: '19th / 22nd*', description: 'Pay all CIS deductions withheld from subcontractors to HMRC. Can be combined with the PAYE/NIC payment.' },
          { name: 'CIS Payment Statements', required: '19th', description: 'Issue a written payment and deduction statement to every subcontractor paid that month. Must show gross amount, materials, and the deduction applied.' },
          { name: 'PAYE / NIC Payment', required: '19th / 22nd*', description: 'Pay all employee Income Tax and National Insurance contributions for the preceding payroll month. Electronic payment deadline is the 22nd.' },
          { name: 'Full Payment Submission (FPS)', required: 'On or before payday', description: 'Submit the FPS to HMRC on or before each pay date. Late FPS triggers automatic penalty notices of £100–£400 per month depending on employee count.' },
          { name: 'Pension Contributions', required: 'Per scheme rules', description: 'Pay employer and employee pension contributions to the pension provider — typically by the 19th or 22nd. Late payment is reported to The Pensions Regulator.' },
        ],
        notes: [
          '* Electronic payment deadline. Cheque/postal payments are due the 19th.',
          'A missed or late CIS300 return attracts penalties starting at £100, rising to £3,000+ depending on how many months late.',
          'Use recurring tasks in this system to surface each obligation on the correct date automatically.',
        ],
      },
      {
        id: 'compliance-annual',
        title: 'Annual Obligations',
        badge: 'Admin',
        description: 'These deadlines fall once per year. Missing any of them carries statutory penalties — several escalate daily.',
        fields: [
          { name: 'P60 to Employees', required: '31 May', description: 'Issue a P60 to every employee who was on the payroll on 5 April. Failure to issue by this date is a statutory offence (£300 penalty + up to £60/day).' },
          { name: 'P11D (Benefits)', required: '6 July', description: 'File P11D forms with HMRC for all employees and directors who received taxable benefits in the previous tax year (company cars, private fuel, loans, private medical). Issue copies to each affected person.' },
          { name: 'P11D(b) + Class 1A NIC', required: '6 July (pay 22 July)', description: 'File the P11D(b) Class 1A NIC declaration and pay the resulting NIC by 22 July electronically. Interest applies on late payment.' },
          { name: 'Corporation Tax Payment', required: '9 months + 1 day after year end', description: 'For a 31 March year end, payment is due 1 January. Small companies pay in one lump sum.' },
          { name: 'CT600 Return', required: '12 months after year end', description: 'For a 31 March year end, the CT600 must be filed by 31 March the following year. £100 penalty immediately; £500 after 6 months.' },
          { name: 'Statutory Accounts (Companies House)', required: '9 months after year end', description: 'For a 31 March year end, file by 31 December. Late filing penalties range from £150 to £1,500 and escalate with delay.' },
          { name: 'Confirmation Statement', required: 'Within 14 days of review date', description: 'File the CS01 with Companies House annually confirming directors, shareholders, and SIC codes. Failure to file is a criminal offence and can result in the company being struck off.' },
          { name: 'Directors\' Self Assessment', required: '31 January (online)', description: 'Both directors must file their Self Assessment return and pay any balancing tax by 31 January. £100 penalty immediately; £10/day after 3 months. A Payment on Account is also due 31 January and 31 July.' },
          { name: 'CIS Gross Payment Status Review', required: 'Each April (HMRC-initiated)', description: 'HMRC reviews GPS annually. Every PAYE, CIS, VAT, and Corporation Tax return and payment must have been on time in the preceding 12 months — a single late payment can trigger automatic withdrawal.' },
        ],
        notes: [
          'CIS Gross Payment Status allows you to receive payments from contractors without deductions (i.e. the full pound rather than 80p). Losing it has an immediate cash flow impact — treat GPS compliance as a board-level priority.',
          'Directors\' P11D information must be passed to them before they can complete their Self Assessment returns.',
        ],
      },
      {
        id: 'compliance-vat',
        title: 'Quarterly VAT',
        badge: 'Admin',
        description: 'VAT returns are filed quarterly. The examples below assume quarters ending March / June / September / December — confirm your own quarter dates with your accountant.',
        fields: [
          { name: 'Q1 (Apr–Jun)', required: 'File and pay by 7 August', description: 'Reconcile VAT records at 30 June and submit via MTD-compliant software. Both the return and payment are due 7 August.' },
          { name: 'Q2 (Jul–Sep)', required: 'File and pay by 7 November', description: 'Return and payment due 7 November.' },
          { name: 'Q3 (Oct–Dec)', required: 'File and pay by 7 February', description: 'Return and payment due 7 February.' },
          { name: 'Q4 (Jan–Mar)', required: 'File and pay by 7 May', description: 'Return and payment due 7 May.' },
          { name: 'VAT Reverse Charge', required: '', description: 'When supplying CIS construction services to another VAT-registered contractor, the domestic reverse charge applies — the customer accounts for VAT, not the supplier. Apply this correctly on all relevant invoices.' },
        ],
        notes: [
          'Making Tax Digital (MTD) requires VAT records to be kept in MTD-compliant software and returns submitted through it.',
          'Retain VAT invoices and receipts for 6 years.',
          'The VAT reverse charge and CIS deductions are separate calculations — a subcontractor invoice may be subject to both.',
        ],
      },
      {
        id: 'compliance-triggered',
        title: 'Triggered & Ongoing Obligations',
        badge: 'Admin',
        description: 'These obligations arise when a specific event occurs — a new subcontractor, a new employee, a payment dispute, or a change in company size. They have no fixed calendar date.',
        fields: [
          { name: 'CIS Subcontractor Verification', required: 'Before first payment', description: 'Verify every new subcontractor with HMRC before making any payment. HMRC confirms the correct deduction rate: 0% (gross), 20% (standard), or 30% (unmatched). Retain the verification reference. Failure to verify means a 30% deduction rate must be applied.' },
          { name: 'Re-verification', required: 'Every 2 years or on status change', description: 'Re-verify subcontractors whose verification is more than 2 years old, or whose tax status has changed.' },
          { name: 'New Employee (FPS)', required: 'On or before first pay date', description: 'Include new starter details on the next FPS. Collect a starter checklist and apply the correct tax code before the first payment.' },
          { name: 'Leaver (FPS + P45)', required: 'On or before final pay date', description: 'Submit an FPS with the leaving date on or before the final pay date. Issue a P45 to the employee.' },
          { name: 'Auto-enrolment Assessment', required: 'Each pay run', description: 'Assess all workers for pension eligibility on every pay run. Auto-enrol any eligible worker aged 22–State Pension age earning above £10,000/year who has not opted out. Write to each newly enrolled worker within 6 weeks.' },
          { name: 'Re-enrolment', required: 'Every 3 years', description: 'Re-enrol any workers who previously opted out and still meet eligibility criteria. Submit a re-declaration of compliance to The Pensions Regulator within 5 months of the re-enrolment date.' },
          { name: 'IR35 Status Assessment', required: 'Before each new engagement', description: 'Assess employment status for each subcontractor engaged through their own limited company. Use HMRC\'s CEST tool and retain the output. CIS registration is not a proxy for self-employment — the two assessments are entirely separate.' },
          { name: 'Construction Act — Payment Notices', required: 'Within 5 days of payment due date', description: 'Issue a payment notice within 5 days of the payment due date stating the sum due. If you intend to pay less, a pay-less notice must be issued before the prescribed period expires — typically 5–7 days before the final payment date. Failure to issue a pay-less notice makes the full notified sum automatically payable.' },
          { name: 'Waste Transfer Notes', required: 'At every collection', description: 'Obtain a signed waste transfer note for every waste collection. Verify the carrier\'s Environment Agency registration number and retain the paperwork for a minimum of 2 years. Breach of duty of care can result in an unlimited fine.' },
        ],
        notes: [
          'CIS and IR35 must be assessed independently. Being deducted at 20% CIS does not mean a worker is self-employed for IR35 purposes.',
          'Pay-when-paid clauses are largely unenforceable under the Construction Act. You cannot withhold payment from a subcontractor solely because your own client has not paid you.',
          'If a retention is not released after the defects liability period without a valid pay-less notice, the full retention is likely payable — adjudication is often the most effective route to recovery.',
        ],
      },
      {
        id: 'compliance-cis-scope',
        title: 'CIS Scope — Landscaping & External Works',
        badge: 'Admin',
        description: 'Not all landscaping and external works activity falls within CIS. Over-deducting damages subcontractor cash flow; under-deducting creates HMRC liability. Assess each contract before invoicing.',
        fields: [
          { name: 'Within CIS', required: '', description: 'Site clearance and preparation; groundworks (drainage, ducting, kerbing); hard landscaping (paths, driveways, patios, retaining walls, steps) forming part of a construction project; external works packages on new-build or refurbishment contracts; fencing and boundary structures; irrigation systems, external lighting, and underground services; any landscaping subcontracted as part of a wider construction contract.' },
          { name: 'Outside CIS', required: '', description: 'Pure horticultural work (planting, maintenance, mowing, pruning, seasonal bedding) where not part of a construction project; grounds maintenance contracts with no construction activity; tree surgery not incidental to a construction operation; supply-only of plants, turf, or materials.' },
          { name: 'Mixed Contracts', required: '', description: 'Where a single contract includes both CIS and non-CIS work, CIS applies only to the construction element. Document the split in the contract and on invoices. If in doubt, treating the whole contract as within CIS is the lower-risk position.' },
          { name: 'Housing Association Contracts', required: '', description: 'Work on HA development sites — even purely soft landscaping — is likely within CIS because it is incidental to a construction project. The test is whether the work is part of or incidental to a construction operation, not the nature of the work itself.' },
        ],
        notes: [
          'Document your CIS scope assessment for each new contract and retain it with the contract file.',
          'HMRC penalties for failing to deduct are more severe than those for over-deducting (which is recoverable by the subcontractor).',
        ],
      },
    ],
  },
];

exports.getHelp = function (req, res) {
  const role = req.user && req.user.role;

  // Map badge strings → which roles may read that article.
  // 'All roles' is visible to everyone with an account.
  const badgeRoles = {
    'All roles':                        ['admin', 'accountant', 'employee', 'subcontractor', 'client', 'hmrc', 'none'],
    'Admin':                            ['admin'],
    'Admin / HR':                       ['admin'],
    'Admin / Accountant':               ['admin', 'accountant'],
    'Admin / Accountant / HMRC':        ['admin', 'accountant', 'hmrc'],
    'Accountant / Admin':               ['admin', 'accountant'],
    'Accountant / Admin / HMRC':        ['admin', 'accountant', 'hmrc'],
    'Employee':                         ['admin', 'employee'],
    'Employee / Subcontractor':         ['admin', 'employee', 'subcontractor'],
    'Admin / Employee / Subcontractor': ['admin', 'employee', 'subcontractor'],
    'Subcontractor':                    ['admin', 'subcontractor'],
    'Client':                           ['admin', 'client'],
    'HMRC':                             ['admin', 'hmrc'],
  };

  const filtered = helpContent
    .map(cat => ({
      ...cat,
      articles: cat.articles.filter(art => {
        const allowed = badgeRoles[art.badge];
        // If we don't recognise the badge, show to admin only.
        if (!allowed) return role === 'admin';
        return allowed.includes(role);
      }),
    }))
    .filter(cat => cat.articles.length > 0);

  res.render('tailwindcss/help/index', {
    title: 'Help',
    helpContent: filtered,
  });
};

// ── Helper: render a nested field table (used in api.ejs via locals) ───────────
function renderFieldTableHtml(fields, group, depth) {
  depth = depth || 0;
  const indent = depth > 0 ? 'pl-' + (depth * 4) : '';
  let rows = '';
  (fields || []).forEach(function(f) {
    const reqBadge = f.required === true || f.required === 'Yes'
      ? '<span class="inline-block text-xs px-2 py-0.5 rounded-full bg-red-100 dark:bg-red-900/30 text-red-700 dark:text-red-400 font-medium">Required</span>'
      : f.required && f.required !== false && f.required !== ''
        ? '<span class="inline-block text-xs px-2 py-0.5 rounded-full bg-amber-100 dark:bg-amber-900/30 text-amber-700 dark:text-amber-400 font-medium">' + f.required + '</span>'
        : '<span class="text-xs text-gray-400 dark:text-gray-600">Optional</span>';
    rows += '<tr class="hover:bg-gray-50 dark:hover:bg-gray-800/40 transition">';
    rows += '<td class="px-4 py-2.5 font-mono text-xs text-gray-800 dark:text-gray-200 ' + indent + '">' + (depth > 0 ? '<span class="text-gray-400 mr-1">└</span>' : '') + f.name + '</td>';
    rows += '<td class="px-4 py-2.5 font-mono text-xs text-indigo-600 dark:text-indigo-400">' + (f.type || '') + '</td>';
    rows += '<td class="px-4 py-2.5">' + reqBadge + '</td>';
    rows += '<td class="px-4 py-2.5 text-sm text-gray-600 dark:text-gray-400 leading-relaxed">' + (f.description || '') + '</td>';
    rows += '</tr>';
    if (f.children && f.children.length) {
      rows += renderFieldTableHtml(f.children, group, depth + 1);
    }
  });
  if (depth > 0) return rows;
  return '<div class="overflow-x-auto rounded-xl border border-gray-200 dark:border-gray-700"><table class="w-full text-sm"><thead><tr class="bg-gray-50 dark:bg-gray-800 text-left"><th class="px-4 py-2.5 font-semibold text-gray-700 dark:text-gray-300 w-52">Field</th><th class="px-4 py-2.5 font-semibold text-gray-700 dark:text-gray-300 w-20">Type</th><th class="px-4 py-2.5 font-semibold text-gray-700 dark:text-gray-300 w-28">Required</th><th class="px-4 py-2.5 font-semibold text-gray-700 dark:text-gray-300">Description</th></tr></thead><tbody class="divide-y divide-gray-100 dark:divide-gray-800">' + rows + '</tbody></table></div>';
}

const methodColors = {
  GET:    'bg-blue-100 dark:bg-blue-900/30 text-blue-700 dark:text-blue-400',
  POST:   'bg-green-100 dark:bg-green-900/30 text-green-700 dark:text-green-400',
  PUT:    'bg-amber-100 dark:bg-amber-900/30 text-amber-700 dark:text-amber-400',
  PATCH:  'bg-orange-100 dark:bg-orange-900/30 text-orange-700 dark:text-orange-400',
  DELETE: 'bg-red-100 dark:bg-red-900/30 text-red-700 dark:text-red-400',
};

function methodBadge(method) {
  const cls = methodColors[method] || 'bg-gray-100 text-gray-700';
  return '<span class="inline-block text-xs font-mono font-bold px-2.5 py-1 rounded-lg ' + cls + '">' + method + '</span>';
}

function methodBadgeSmall(method) {
  const cls = methodColors[method] || 'bg-gray-100 text-gray-700';
  return '<span class="flex-shrink-0 inline-block text-[10px] font-mono font-bold px-1.5 py-0.5 rounded ' + cls + '">' + method + '</span>';
}

exports.getApiDocs = function (req, res) {
  res.render('tailwindcss/help/api', {
    title: 'KashFlow API',
    apiDocs,
    renderFieldTable: function(fields, group) { return renderFieldTableHtml(fields, group, 0); },
    methodBadge,
    methodBadgeSmall,
  });
};
